apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nonlnrsine
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containers:
      - image: mohakamg/sineestimator:nonlinear
